# SPDX-License-Identifier: PMPL-1.0-or-later

name = "StdlibMerger"
uuid = "a1b2c3d4-e5f6-7890-1234-56789abcdef0"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
TreeSitter = "5d88e7e3-d984-41fb-a480-87c2c8131b9f"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
julia = "1.9"
HTTP = "1.9"
JSON3 = "1.13"
YAML = "0.4"
StringDistances = "0.11"
TreeSitter = "0.2"
MLStyle = "0.4"
ArgParse = "1.1"
ProgressMeter = "1.9"
